#!/bin/sh /etc/rc.common
# Copyright (C) 2019 [CTCGFW] Project OpenWRT

START=91
STOP=10

CONFIG="baidupcs-web"

config_t_get() {
	local index=0
	[ -n "$4" ] && index=$4
	local ret=$(uci get $CONFIG.$1.$2 2>/dev/null)
	echo ${ret:=$3}
}

ENABLED=$(config_t_get service enable)
PORT=$(config_t_get service port)
ENARIA=$(config_t_get service en_aria2)
DLPATH=$(config_t_get service download_path)
AU_VALUE=$(config_t_get service au_value)
AS_VALUE=$(config_t_get service as_value)
AP_VALUE=$(config_t_get service ap_value)
PD_VALUE=$(config_t_get service pd_value)
PROJDIR=$(echo -n $(uci get baidupcs-web.service.project_path) | sed 's/\/$//')
BAIDUPCS="$PROJDIR/baidupcs-web"

if [ "$AP_VALUE" == "" ];then
	PRE=""
else
	PRE="--ap $AP_VALUE"
fi

if [ "$PD_VALUE" == "" ];then
	PDURL=""
else
	PDURL="--pd $PD_VALUE"
fi

if [ "$AS_VALUE" == "" ];then
	ARIARPC="$PRE $PDURL"
else
	ARIARPC="--au $AU_VALUE --as $AS_VALUE $PRE $PDURL"
fi

start() {	

	[ "$ENABLED" == "1" ] || exit 0

	$BAIDUPCS config set --savedir $DLPATH >/dev/null 2>&1 &

	if [ "$ENARIA" == "1" ];then
		$BAIDUPCS -a $ARIARPC >/dev/null 2>&1 &
	else	
		$BAIDUPCS web --port $PORT --access >/dev/null 2>&1 &
	fi
	
}

stop() {
	killall baidupcs-web >/dev/null 2>&1
}

restart() {
    stop
    sleep 2
    start
}
