#!/bin/sh /etc/rc.common
# Copyright (C) 2019 [CTCGFW] Project OpenWRT

START=92
STOP=10

CONFIG="filebrowser"

config_t_get() {
	local index=0
	[ -n "$4" ] && index=$4
	local ret=$(uci get $CONFIG.@$1[$index].$2 2>/dev/null)
	echo ${ret:=$3}
}

ENABLED=$(config_t_get filebrowser enable)
ADDRTYPE=$(config_t_get filebrowser addrtype)
PORT=$(config_t_get filebrowser port)
ROOTPATH=$(config_t_get filebrowser root_path)
ADMIN=$(config_t_get filebrowser admin)
LOG_EN=$(config_t_get filebrowser Enabled)
LOG_DIR=$(echo -n $(uci get filebrowser.@filebrowser[0].log_path) | sed 's/\/$//')
PROJDIR=$(echo -n $(uci get filebrowser.@filebrowser[0].project_path) | sed 's/\/$//')
FILEBROWSER="$PROJDIR/filebrowser"
DB_PATH="$PROJDIR/filebrowser.db"

if [ "$LOG_EN" == "false" ];then
    LOGED=""
else
    [ -d "$LOG_DIR" ] || LOG_DIR="/tmp"
	LOGED="-l $LOG_DIR/filebrowser.log"
fi

if [ "$ADDRTYPE" == "lan" ];then
	ADDR="$(uci get network.lan.ipaddr)"
elif [ "$ADDRTYPE" == "wan" ];then
	ADDR="0.0.0.0"
fi

start() {	

	[ "$ENABLED" == "1" ] || exit 0

    if [ ! -f "$DB_PATH" ];then
        PASSWORD=$($FILEBROWSER hash "$(uci get filebrowser.@filebrowser[0].password)" | sed 's/$/\$/g')
	$FILEBROWSER -a $ADDR -p $PORT -r $ROOTPATH -d $DB_PATH $LOGED --username $ADMIN --password "${PASSWORD}" >/dev/null 2>&1 &
    else
        $FILEBROWSER -a $ADDR -p $PORT -r $ROOTPATH -d $DB_PATH $LOGED >/dev/null 2>&1 &
    fi
}

stop() {
	ps -w | grep -v grep | grep "filebrowser -a" | awk '{print $1}' | xargs kill -9 >/dev/null 2>&1 &
}

restart() {
    stop
    sleep 2
    start
}
