#!/bin/sh /etc/rc.common
# Copyright (C) 2019 [CTCGFW] Project OpenWRT

START=93
STOP=10

CONFIG="alist"

config_t_get() {
	local index=0
	[ -n "$4" ] && index=$4
	local ret=$(uci get $CONFIG.@$1[$index].$2 2>/dev/null)
	echo ${ret:=$3}
}

ENABLED=$(config_t_get alist enable)
ADDRTYPE=$(config_t_get alist addrtype)
PORT=$(config_t_get alist port)
SSL_EN=$(config_t_get alist ssl)
SSL_CERT=$(config_t_get alist ssl_cert)
SSL_KEY=$(config_t_get alist ssl_key)
TMPDIR=$(config_t_get alist temp_dir)
LOG_EN=$(config_t_get alist loged)
PROGDIR=$(echo -n $(uci get alist.@alist[0].project_path) | sed 's/\/$//')
ALIST="$PROGDIR/alist"

if [ "$ADDRTYPE" == "lan" ];then
	ADDR="$(uci get network.lan.ipaddr)"
elif [ "$ADDRTYPE" == "wan" ];then
	ADDR="0.0.0.0"
fi

start() {	

	[ $ENABLED != 1 ] && return 1

    mkdir -p $TMPDIR

    cat /dev/null > $TMPDIR/server.log
    cat /dev/null > $TMPDIR/alist.log
    cat > $PROGDIR/config.json << EOF
{
  "force": false,
  "address": "$ADDR",
  "port": $PORT,
  "jwt_secret": "random generated",
  "token_expires_in": 48,
  "site_url": "",
  "cdn": "",
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "$PROGDIR/data.db",
    "table_prefix": "x_",
    "ssl_mode": ""
  },
  "scheme": {
    "https": $SSL_EN,
    "cert_file": "$SSL_CERT",
    "key_file": "$SSL_KEY"
  },
  "temp_dir": "$TMPDIR",
  "log": {
    "enable": $LOG_EN,
    "name": "$TMPDIR/server.log",
    "max_size": 10,
    "max_backups": 5,
    "max_age": 28,
    "compress": false
  }
}
EOF

    $ALIST server --data $PROGDIR >> $TMPDIR/alist.log 2>&1 &
}

stop() {
	ps -w | grep -v grep | grep "alist server" | awk '{print $1}' | xargs kill -9 >/dev/null 2>&1 &
}

restart() {
    stop
    sleep 1
    start
}
