#!/bin/sh /etc/rc.common
# Copyright (C) 2019 [CTCGFW] Project OpenWRT

START=99
STOP=11

CONFIG="alist"

config_t_get() {
	local index=0
	[ -n "$4" ] && index=$4
	local ret=$(uci get $CONFIG.@$1[$index].$2 2>/dev/null)
	echo ${ret:=$3}
}

ENABLED=$(config_t_get alist enable)
ADDRTYPE=$(config_t_get alist addrtype)
PORT=$(config_t_get alist port)
SSL_EN=$(config_t_get alist ssl)
CERTDIR=$(config_t_get alist ssl_cert)
KEYDIR=$(config_t_get alist ssl_key)
TMPDIR=$(config_t_get alist temp_dir)
LOG_EN=$(config_t_get alist log)
PROGDIR=$(echo -n $(uci get alist.@alist[0].project_path) | sed 's/\/$//')
PROG="$PROGDIR/alist"

start() {
	[ $ENABLED != 1 ] && return 1
	
	mkdir -p $TMPDIR
	
	if [ "$ADDRTYPE" == "lan" ];then
		listen_addr="$(uci get network.lan.ipaddr)"
	else
		listen_addr="0.0.0.0"
	fi
	
	cat /dev/null > $TMPDIR/server.log
    cat > $PROGDIR/config.json <<EOF
{
  "force": false,
  "address": "$listen_addr",
  "port": $PORT,
  "jwt_secret": "random generated",
  "token_expires_in": 48,
  "site_url": "",
  "cdn": "",
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "$PROGDIR/data.db",
    "table_prefix": "x_",
    "ssl_mode": ""
  },
  "scheme": {
    "https": $SSL_EN,
    "cert_file": "$CERTDIR",
    "key_file": "$KEYDIR"
  },
  "temp_dir": "$TMPDIR",
  "log": {
    "enable": $LOG_EN,
    "name": "$TMPDIR/server.log",
    "max_size": 10,
    "max_backups": 5,
    "max_age": 28,
    "compress": false
  }
}
EOF

	$PROG server --data $PROGDIR > $TMPDIR/alist.log 2>&1 &

}

stop() {
	killall alist >/dev/null 2>&1
}

restart() {
	stop
    sleep 2
    start
}
