#!/bin/sh

[ -f /etc/10_system.js ] && mv /etc/10_system.js /www/luci-static/resources/view/status/include/10_system.js
[ -f /etc/luci ] && mv /etc/luci /usr/libexec/rpcd/luci
[ -f /etc/luci-base.json ] && mv /etc/luci-base.json /usr/share/rpcd/acl.d/luci-base.json
[ -f /etc/upnp_status.htm ] && mv /etc/upnp_status.htm /usr/lib/lua/luci/view/upnp_status.htm

exit 0
